# Generated by Django 5.0.6 on 2025-11-08 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtimelog',
            name='log_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 8, 18, 28, 6, 519569, tzinfo=datetime.timezone.utc)),
        ),
    ]
