# Generated by Django 5.0.6 on 2025-11-08 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teamtimelog_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtimelog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
