# Generated by Django 5.0.6 on 2025-11-04 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_time', models.DurationField(help_text="Target time to spend (e.g., '10:00:00' for 10 hours)")),
                ('real_time', models.DurationField(default=datetime.timedelta(0), help_text='Actual time spent so far')),
                ('completed', models.BooleanField(default=False)),
                ('days_of_the_week', models.CharField(blank=True, max_length=7)),
                ('importance_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('minutes', models.IntegerField(help_text='Time spent in minutes for this log')),
            ],
        ),
    ]
