# Generated by Django 4.2.25 on 2025-10-31 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_teamtak_useraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamTak',
            new_name='TeamTask',
        ),
    ]
